partial interface WorkerGlobalScope {
    [Conditional=CHANNEL_MESSAGING] attribute MessageChannelConstructor MessageChannel;
    attribute MessageEventConstructor MessageEvent;
    attribute BlobConstructor Blob;
    [Conditional=BLOB] attribute DOMURLConstructor URL;
    attribute EventSourceConstructor EventSource;
};
