#!/bin/bash
# Copyright 2014 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# git_squash_branch.py -- Collapses the current branch to a single commit.

. $(type -P python_git_runner.sh)