#!/bin/bash
# Copyright 2014 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# git_mark_merge_base.py -- Manually set the merge base for the current branch.

. $(type -P python_git_runner.sh)
