#!/bin/bash
# Copyright 2014 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# git_freezer.py freeze -- a git-command to suspend all existing working
# directory modifications. This can be reversed with the 'git thaw' command.

SCRIPT=git_freezer.py
set -- freeze "$@"
. $(type -P python_git_runner.sh)
