#!/bin/bash
# Copyright 2014 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# git_map.py -- a git-command for presenting a graphical view of the git
# history.

. $(type -P python_git_runner.sh) | less -R