#!/bin/bash
# Copyright 2014 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# git_rebase_update.py -- Update remote sources, and use rebase to update all
# branches in this repo.

. $(type -P python_git_runner.sh)