#!/bin/bash
# Copyright 2013 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# git_number.py - a git-command for calculating and displaying the generation
# number of a commit.

. $(type -P python_git_runner.sh)
