#!/bin/sh
# Copyright (c) 2012 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# git-cl -- a git-command for integrating reviews on Rietveld
# Copyright (C) 2008 Evan Martin <martine@danga.com>

# Test if this script is running under a MSys install.  If it is, we will
# hardcode the path to Python where possible.
OUTPUT="$(uname | grep 'MINGW')"
MINGW=$?

if [ $MINGW = 0 ]; then
  base_dir="${0%\\*}"
else
  base_dir=$(dirname "$0")
fi

# Uncomment this line if you never use gclient.
# "$base_dir"/update_depot_tools

if [ -d "$base_dir/python_bin" -a $MINGW = 0 ]; then
  PYTHONDONTWRITEBYTECODE=1 exec "$base_dir/python_bin/python.exe" "$base_dir"/git_cl.py "$@"
else
  PYTHONDONTWRITEBYTECODE=1 exec "$base_dir/git_cl.py" "$@"
fi
